# Generated by Django 4.1.2 on 2022-10-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmr_food', '0005_alter_menu_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
