# Generated by Django 4.1.2 on 2022-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmr_food', '0003_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='comida',
            field=models.CharField(choices=[('taco', 'Taco'), ('hamburguesa', 'Hamburguesa'), ('pizza', 'Pizza'), ('empanada', 'Empanada')], default='hamburguesa', max_length=20),
        ),
    ]
