# Generated by Django 4.1.2 on 2022-10-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMR_Food', '0004_alter_menu_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='comida',
            field=models.CharField(choices=[('Tacos', 'tacos'), ('Hamburguesa', 'hamburguesa'), ('Pizza', 'pizza'), ('Empanadas', 'empanadas')], default='hamburguesa', max_length=20),
        ),
    ]
