# Generated by Django 4.1.2 on 2022-10-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMR_Food', '0007_informacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='comida',
            field=models.CharField(choices=[('Tacos', 'tacos'), ('Hamburguesa', 'hamburguesa'), ('Pizza', 'pizza'), ('Empanadas', 'empanadas'), ('papas-fritas', 'Papas-Fritas'), ('Grow-Cerveza', 'grow-cerveza'), ('Super-Pancho', 'super-pancho'), ('Lata-Gaseosa', 'lata-gaseosa')], default='hamburguesa', max_length=20),
        ),
    ]
