# Generated by Django 4.1.2 on 2022-11-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmr_food', '0013_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descripcion',
            field=models.CharField(default='sin descripcion', max_length=250),
        ),
    ]
