# Generated by Django 4.1.2 on 2022-11-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmr_food', '0016_post_remove_cliente_direccion_remove_cliente_mail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
