# Generated by Django 4.1.2 on 2022-11-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmr_food', '0017_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
